name: SPE11CSP CI

on:
  push:
    branches:
      - test/gha
    pull_request:
    workflow_dispatch:


jobs:

  test_one_group:

    runs-on: ubuntu-22.04
    name : ${{ matrix.version }}-${{ matrix.data_type }}
    matrix :
      version: [ a , b ]
      data_type : [ sparse, dense ]
      output : ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }}
      steps :
        - run : python3 -m pip3 install pandas numpy matplotlib
        - run : python3 script/main.py --spe ${{ matrix.version }} --${{ matrix.data_type }} -i ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }} -o ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }} --units h g Pa



  
