name: SPE11CSP CI

on:
  push:
    branches:
      - test/gha


jobs:

  test_one_group:

    runs-on: ubuntu-22.04
    name : ${{ matrix.version }}-${{ matrix.data_type }}
    strategy:
      fail-fast: false
      matrix :
        name: [ groupA ]
        version: [ a , b ]
        data_type : [ sparse, dense ]
    steps :
      - uses: actions/checkout@v1
      - name : Setup python
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel pandas numpy matplotlib pickle
      - name : Running driver
        run : python3 script/main.py --spe ${{ matrix.version }} --${{ matrix.data_type }} -i ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }} -o ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }} --units h g Pa
      - name : Upload generated pngs
        uses : actions/upload-artifact@v4
        with :
          name : illustrations-${{ matrix.name }}-${{ matrix.version }}-${{ matrix.data_type }}
          path : ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }}/*.png
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: downloads-${{ matrix.name }}-${{ matrix.version }}-${{ matrix.data_type }}
          path: ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }}/
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: test/gha
          commit_options: '--no-verify --signoff'
          commit_author: Author <actions@github.com>
          status_options: '--untracked-files=no'
          skip_dirty_check: true

  
