name: SPE11CSP CI

on:
  push:
    branches:
      - test/gha


jobs:

  test_one_group:

    runs-on: ubuntu-22.04
    name : ${{ matrix.version }}-${{ matrix.data_type }}
    strategy:
      fail-fast: false
      matrix :
        name: [ groupA ]
        version: [ a , b ]
        data_type : [ sparse, dense ]
    steps :
      - name : Setup python
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel pandas numpy matplotlib
      - name : Running driver
        run : python3 ../script/main.py --spe ${{ matrix.version }} --${{ matrix.data_type }} -i ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }} -o ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }} --units h g Pa



  
