name: SPE11CSP CI

on:
  push:
    branches:
      - test/gha


jobs:

  test_one_group:

    runs-on: ubuntu-22.04
    name : ${{ matrix.version }}-${{ matrix.data_type }}
    strategy:
      fail-fast: false
      matrix :
        version: [ a , b ]
        data_type : [ sparse, dense ]
        output : ${{ matrix.name }}/${{ matrix.version }}/${{ matrix.data_type }}
    steps :
      - run : python3 -m pip3 install pandas numpy matplotlib
      - run : python3 script/main.py --spe ${{ matrix.version }} --${{ matrix.data_type }} -i ${{ matrix.output }} -o ${{ matrix.output }} --units h g Pa



  
